"""Remove weekly quota from categories

Revision ID: 0ce7bc274da5
Revises: 670977d5e420
Create Date: 2026-08-29 21:18:11.653074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce7bc274da5'
down_revision: Union[str, Sequence[str], None] = '670977d5e420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'weekly_quota')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.add_column(
        "categories",
        sa.Column(
            "weekly_quota",
            sa.Integer(),
            nullable=False,
            server_default="0"
        )
    )