"""Add workout completion tracking

Revision ID: 7349b6c1ecfc
Revises: 9dea58bc73f1
Create Date: 2026-09-13 15:00:01.956117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7349b6c1ecfc'
down_revision: Union[str, Sequence[str], None] = '9dea58bc73f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_days', sa.Column('completed', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('workout_days', sa.Column('performed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_days', 'performed_at')
    op.drop_column('workout_days', 'completed')
    # ### end Alembic commands ###
